name: Test

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run the E2E tests
        run: |
          pnpm run build
          pnpm run e2e:headless